language: node_js
node_js:
  - 8.9.3
  - 9
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
  - ./tests/travis/start_consul.sh
  - 'curl -k https://mfelten.de/kronos/kronos-service-manager-ui.tar|tar xvfz -'
script:
  - npm run cover
after_script:
  - codecov
  - cat ./build/coverage/lcov.info | coveralls
  - npm run docs
after_success:
  - npm run semantic-release
