language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
notifications:
  email:
    - torstenlink@gmx.de
before_script:
  - ./tests/travis/start_consul.sh
  - 'curl -k https://mfelten.dynv6.net/binaries/kronos/kronos-service-manager-ui.tar|tar xvfz -'
jobs:
  include:
    - stage: test
      node_js:
        - 13.8.0
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
    - stage: docs
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm install -g --production coveralls codecov
        - npm run cover
        - codecov
        - cat ./coverage/lcov.info | coveralls
        - npm run lint
        - npm run docs
